server:
  port: 9000

keyPath:
  auth-server-public-key-file-path: test_public_key.der
  auth-server-private-key-file-path:  test_private_key.der

logging:
  level:
    org.springframework.security: trace

spring:
  application:
    name: bookshare-authorization-server

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookshare
    password: root
    username: root

  sql:
    init:
      mode: never